# Generated by Django 4.2.2 on 2026-02-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studioprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='studioprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='studios/', verbose_name='Cover Image'),
        ),
    ]
