# Generated by Django 4.2.2 on 2026-02-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_remove_studioprofile_updated_at_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount Price'),
        ),
    ]
