# Generated by Django 4.2.2 on 2026-01-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDIO', 'Studio'), ('CUSTOMER', 'Customer'), ('UNASSIGNED', 'Unassigned')], default='UNASSIGNED', max_length=50, verbose_name='Role'),
        ),
    ]
